version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    networks:
      - my-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 3s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  go-app:
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      postgres:
        condition: service_healthy


networks:
  my-network:
volumes:
    postgres-data: